"""empty message

Revision ID: 0e63d1256e56
Revises: 8e28958c34ff
Create Date: 2023-08-31 19:12:01.211869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e63d1256e56'
down_revision = '8e28958c34ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id_plant', sa.Integer(), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('path_template_docx_file', sa.String(), nullable=False),
    sa.Column('path_map_data_json_file', sa.String(), nullable=False),
    sa.Column('path_form_xlsx_file', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_plant'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['id_type'], ['types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    op.drop_table('types')
    op.drop_table('plants')
    # ### end Alembic commands ###
