"""empty message

Revision ID: 7938adbb1e54
Revises: 85164fb4bb04
Create Date: 2023-09-12 21:16:31.248257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7938adbb1e54'
down_revision = '85164fb4bb04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('date_verification',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('date_next_verification',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('certificate_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('certificate_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('date_next_verification',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('date_verification',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
