"""empty message

Revision ID: 85164fb4bb04
Revises: f4238657ff50
Create Date: 2023-09-12 13:05:04.465791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85164fb4bb04'
down_revision = 'f4238657ff50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.alter_column('number',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
