"""empty message

Revision ID: f4238657ff50
Revises: 0e63d1256e56
Create Date: 2023-09-11 21:34:22.029664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4238657ff50'
down_revision = '0e63d1256e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type_device',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('id_type', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date_verification', sa.Date(), nullable=False),
    sa.Column('date_next_verification', sa.Date(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id_type'], ['type_device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    op.drop_table('type_device')
    # ### end Alembic commands ###
